if ~evalin('base','exist(''CtrlsVer'',''var'');')

    Simulink.defineIntEnumType('CtrlsVerEnum', ...
        {'CtrlA_Original','CtrlB_Sneak_fix','CtrlC_ExecOrder_fix', ...
        'CtrlD_ExecOrderSneak_fix','CtrlE_ExecOrderSneakDblReject_fix',...
        'CtrlF_ExecOrderLimCheck_fix','CtrlG_ExecOrderLimCheckSneak_fix',...
        'CtrlH_All_fix'},(1:8)');

    evalin('base','CtrlsVer = CtrlsVerEnum.CtrlA_Original;');
        
end

if ~evalin('base','exist(''Prop2Prove'',''var'');')
    
    Simulink.defineIntEnumType('PropEnum', ...
        {'Prop_none','Prop_tspeed_LE_90','Prop_coast', ...
        'Prop_coast_pulse','Prop_coast_pulse_eml',...
        'Prop_coast_minspeed','Prop_accel_overspeed'},(1:7)');
    
    evalin('base','Prop2Prove = PropEnum.Prop_none;');

end